name: drupal-commerce
recipe: drupal11
config:
  webroot: web
  php: '8.4'
  composer_version: '2-latest'
  xdebug: debug
  drush: ^13
  database: mysql:8.4

services:
  appserver:
    overrides:
      environment:
        DRUSH_OPTIONS_URI: "http://drupal-commerce.lndo.site/"

  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database

proxy:
  appserver:
    - drupal-commerce.lndo.site
  phpmyadmin:
    - pma.drupal-commerce.lndo.site

tooling:
  drupal:
    service: appserver
    cmd: /app/vendor/bin/drupal --root=/app/web
